CREATE DATABASE DEMO_SC_{{ENV}};
CREATE SCHEMA DEMO_SC;
CREATE TABLE HELLO_WORLD
(
   FIRST_NAME VARCHAR
  ,LAST_NAME VARCHAR
);

CREATE TABLE CUSTOMERS
(
   CUSTOMER_ID VARCHAR
  ,CUSTOMER_NAME VARCHAR
);