CREATE DATABASE DEMO_SC1_{{ENV}};
CREATE SCHEMA DEMO_SC1;
CREATE TABLE HELLO_WORLD_DEMO
(
   FIRST_NAME VARCHAR
  ,LAST_NAME VARCHAR
);

CREATE TABLE CUSTOMERS_DEMO
(
   CUSTOMER_ID VARCHAR
  ,CUSTOMER_NAME VARCHAR
);