name: snowflake-devops-demo

on:
  push:
    branches:
      - main
    paths:
      - 'migrations/**'

  workflow_dispatch:

jobs:
  deploy-snowflake-changes-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install schemachange
        run: |
          pip install --upgrade pip
          pip install schemachange

      - name: Create schemachange connections.toml
        env:
          SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
          SF_USERNAME: ${{ secrets.SF_USERNAME }}
          SF_PASSWORD: ${{ secrets.SF_PASSWORD }}
          SF_ROLE: ${{ secrets.SF_ROLE }}
          SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
          SF_DATABASE: ${{ secrets.SF_DATABASE }}
          SF_SCHEMA: ${{ secrets.SF_SCHEMA }}
        run: |
          cat <<EOF > connections.toml
          [connections.default]
          account = "${SF_ACCOUNT}"
          user = "${SF_USERNAME}"
          password = "${SF_PASSWORD}"
          role = "${SF_ROLE}"
          warehouse = "${SF_WAREHOUSE}"
          database = "${SF_DATABASE}"
          schema = "${SF_SCHEMA}"
          EOF

      - name: Run schemachange deployment
        run: |
          schemachange -f migrations -c connections.toml -a default --create-change-history-table
